In [1]:
import numpy as np

In [2]:
narray = np.arange(15).reshape(3, 5)

In [3]:
narray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
narray.shape

(3, 5)

In [5]:
narray.ndim

2

In [6]:
narray.dtype.name

'int32'

In [7]:
narray.itemsize

4

In [8]:
narray.data

In [9]:
type(narray)

numpy.ndarray

In [10]:
narray2 = np.linspace(5, 15, 100)

In [11]:
narray2

array([ 5.        ,  5.1010101 ,  5.2020202 ,  5.3030303 ,  5.4040404 ,
        5.50505051,  5.60606061,  5.70707071,  5.80808081,  5.90909091,
        6.01010101,  6.11111111,  6.21212121,  6.31313131,  6.41414141,
        6.51515152,  6.61616162,  6.71717172,  6.81818182,  6.91919192,
        7.02020202,  7.12121212,  7.22222222,  7.32323232,  7.42424242,
        7.52525253,  7.62626263,  7.72727273,  7.82828283,  7.92929293,
        8.03030303,  8.13131313,  8.23232323,  8.33333333,  8.43434343,
        8.53535354,  8.63636364,  8.73737374,  8.83838384,  8.93939394,
        9.04040404,  9.14141414,  9.24242424,  9.34343434,  9.44444444,
        9.54545455,  9.64646465,  9.74747475,  9.84848485,  9.94949495,
       10.05050505, 10.15151515, 10.25252525, 10.35353535, 10.45454545,
       10.55555556, 10.65656566, 10.75757576, 10.85858586, 10.95959596,
       11.06060606, 11.16161616, 11.26262626, 11.36363636, 11.46464646,
       11.56565657, 11.66666667, 11.76767677, 11.86868687, 11.96

In [12]:
narray_zero = np.zeros((3, 3))

In [13]:
narray_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
npRepeatArray = np.repeat('10', 20)

In [15]:
npRepeatArray

array(['10', '10', '10', '10', '10', '10', '10', '10', '10', '10', '10',
       '10', '10', '10', '10', '10', '10', '10', '10', '10'], dtype='<U2')

In [16]:
type(npRepeatArray)

numpy.ndarray

In [26]:
np.random.shuffle(narray)

In [27]:
print(narray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [30]:
np.prod(narray, axis=1)

array([     0,  15120, 240240])

In [31]:
np.signbit(narray)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [33]:
np.reciprocal(narray2)

array([0.2       , 0.1960396 , 0.19223301, 0.18857143, 0.18504673,
       0.18165138, 0.17837838, 0.17522124, 0.17217391, 0.16923077,
       0.16638655, 0.16363636, 0.16097561, 0.1584    , 0.15590551,
       0.15348837, 0.15114504, 0.14887218, 0.14666667, 0.14452555,
       0.14244604, 0.14042553, 0.13846154, 0.13655172, 0.13469388,
       0.13288591, 0.13112583, 0.12941176, 0.12774194, 0.12611465,
       0.1245283 , 0.12298137, 0.12147239, 0.12      , 0.11856287,
       0.11715976, 0.11578947, 0.11445087, 0.11314286, 0.11186441,
       0.11061453, 0.10939227, 0.10819672, 0.10702703, 0.10588235,
       0.1047619 , 0.10366492, 0.10259067, 0.10153846, 0.10050761,
       0.09949749, 0.09850746, 0.09753695, 0.09658537, 0.09565217,
       0.09473684, 0.09383886, 0.09295775, 0.09209302, 0.09124424,
       0.09041096, 0.08959276, 0.08878924, 0.088     , 0.08722467,
       0.08646288, 0.08571429, 0.08497854, 0.08425532, 0.0835443 ,
       0.08284519, 0.08215768, 0.08148148, 0.08081633, 0.08016

In [34]:
narray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
np.sum(narray, axis=0)

array([15, 18, 21, 24, 27])

In [36]:
np.exp(narray)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06]])

In [37]:
np.sin(narray)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736]])

In [39]:
np.cos(narray)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722]])

In [40]:
np.tan(narray)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00, -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00]])

In [45]:
rad_array = np.radians(narray)

In [46]:
rad_array

array([[0.        , 0.01745329, 0.03490659, 0.05235988, 0.06981317],
       [0.08726646, 0.10471976, 0.12217305, 0.13962634, 0.15707963],
       [0.17453293, 0.19198622, 0.20943951, 0.2268928 , 0.2443461 ]])

In [47]:
degree_array = np.degrees(narray)

In [48]:
degree_array

array([[  0.        ,  57.29577951, 114.59155903, 171.88733854,
        229.18311805],
       [286.47889757, 343.77467708, 401.07045659, 458.3662361 ,
        515.66201562],
       [572.95779513, 630.25357464, 687.54935416, 744.84513367,
        802.14091318]])

In [49]:
np.sinh(narray)

array([[0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
        2.72899172e+01],
       [7.42032106e+01, 2.01713157e+02, 5.48316123e+02, 1.49047883e+03,
        4.05154190e+03],
       [1.10132329e+04, 2.99370708e+04, 8.13773957e+04, 2.21206696e+05,
        6.01302142e+05]])

In [50]:
np.cosh(narray)

array([[1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
        2.73082328e+01],
       [7.42099485e+01, 2.01715636e+02, 5.48317035e+02, 1.49047916e+03,
        4.05154203e+03],
       [1.10132329e+04, 2.99370709e+04, 8.13773957e+04, 2.21206696e+05,
        6.01302142e+05]])

In [51]:
np.tanh(narray)

array([[0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ],
       [0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])